version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    restart: on-failure
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=Abc123++
      - MYSQL_DATABASE=xserverless
      - MYSQL_USER=xserverless
      - MYSQL_PASSOWRD=Abc123++
    ports:
      - 3306:3306
    networks:
      xserverless_network:
        ipv4_address: 172.200.0.2
        aliases:
          - mariadb

  tracker:
    image: season/fastdfs:1.2
    restart: on-failure
    volumes:
      - ./fastdfs/data/tracker:/fastdfs/tracker/data
      - ./fastdfs/config/client.conf:/etc/fdfs/client.conf
    ports:
      - 22122:22122
    networks:
      xserverless_network:
        ipv4_address: 172.200.1.2
        aliases:
          - tracker
    command:
      - "tracker"

  storage:
    image: season/fastdfs:1.2
    restart: on-failure
    depends_on:
      - tracker
    volumes:
      - ./fastdfs/data/storage:/fastdfs/store_path
    environment:
      - TRACKER_SERVER=172.200.1.2:22122
    ports:
      - 23000:23000
    networks:
      xserverless_network:
        ipv4_address: 172.200.1.3
    command:
      - "storage"

  nginx:
    image: season/fastdfs:1.2
    restart: on-failure
    depends_on:
      - tracker
    volumes:
      - ./fastdfs/data/storage:/fastdfs/store_path
      - ./fastdfs/config/nginx.conf:/etc/nginx/conf/nginx.conf
    environment:
      - TRACKER_SERVER=172.200.1.2:22122
    ports:
      - 22080:80
    networks:
      xserverless_network:
        ipv4_address: 172.200.1.4
    command:
      - "nginx"

  redis:
    image: redis
    container_name: redis
    restart: on-failure
    networks:
      xserverless_network:
        ipv4_address: 172.200.2.2
        aliases:
          - redis

  gateway:
    image: xserverless/gateway:0.0.1-SNAPSHOT
    container_name: gateway
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./gateway:/root/gateway
    entrypoint:
      - /usr/bin/java
      - -jar
      - gateway-0.0.1-SNAPSHOT.jar
    depends_on:
      - runtime
    networks:
      xserverless_network:
        ipv4_address: 172.200.3.2
        aliases:
          - gateway
  runtime:
    image: xserverless/runtime:0.0.1-SNAPSHOT
    container_name: runtime
    volumes:
      - ./runtime:/root/runtime
    entrypoint:
      - /usr/bin/java
      - -jar
      - runtime-0.0.1-SNAPSHOT.jar
    networks:
      xserverless_network:
        ipv4_address: 172.200.3.3
        aliases:
          - runtime
  dev-center:
    image: xserverless/runtime:0.0.1-SNAPSHOT
    container_name: dev-center
    volumes:
      - ./dev-center:/root/runtime
    entrypoint:
      - /usr/bin/java
      - -jar
      - dev-center-0.0.1-SNAPSHOT.jar
    networks:
      xserverless_network:
        ipv4_address: 172.200.3.4
        aliases:
          - dev-center

  dev-center-web:
    image: xserverless/nginx:0.0.1-SNAPSHOT
    container_name: dev-center-web
    depends_on: 
      - dev-center
    ports:
      - 8080:80
    volumes:
      - ./dev-center-web/nginx:/root/nginx
      - ./dev-center-web/www:/root/www
    networks:
      xserverless_network:
        ipv4_address: 172.200.3.5
        aliases:
          - dev-center-web

networks:
  xserverless_network:
    ipam:
      config:
        - subnet: 172.200.0.0/16
          gateway: 172.200.0.1
