server:
  port: 0

xserver:
  domain: xserverless.net
  port: 80

xfdfs:
  trackerServer: tracker:22122

spring:
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:mariadb://mariadb:3306/xserverless
    username: xserverless
    password: Abc123++
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  data:
    redis:
      repositories:
        enabled: false

logging:
  level:
    io.xserverless: debug