server:
  port: 80

xfdfs:
  trackerServer: tracker:22122
  # addressMapping: 172.200.1.3:23000=172.200.3.1:23000

spring:
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:mariadb://tracker:3306/xserverless
    username: xserverless
    password: Abc123++
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  data:
    redis:
      repositories:
        enabled: false
  main:
    web-application-type: none

logging:
  level:
    io.xserverless: debug